-- Garante que o role usado pelo dbt (definido em dbt/amazon_pipeline/profiles.yml.example)
-- tenha acesso ao warehouse/database/schemas do projeto.

GRANT USAGE ON WAREHOUSE ${SNOWFLAKE_WAREHOUSE} TO ROLE ${SNOWFLAKE_ROLE};
GRANT USAGE ON DATABASE ${SNOWFLAKE_DATABASE} TO ROLE ${SNOWFLAKE_ROLE};
GRANT USAGE ON SCHEMA ${SNOWFLAKE_DATABASE}.RAW TO ROLE ${SNOWFLAKE_ROLE};
GRANT ALL ON SCHEMA ${SNOWFLAKE_DATABASE}.ANALYTICS TO ROLE ${SNOWFLAKE_ROLE};
GRANT SELECT ON ALL TABLES IN SCHEMA ${SNOWFLAKE_DATABASE}.RAW TO ROLE ${SNOWFLAKE_ROLE};
GRANT SELECT ON FUTURE TABLES IN SCHEMA ${SNOWFLAKE_DATABASE}.RAW TO ROLE ${SNOWFLAKE_ROLE};
